# Core
db:
  redis:
    host: redis
    port: 6379
    namespace: EG

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000

plugins:
  express-gateway-keycloak:
    package: express-gateway-keycloak
    keycloakConfig:
      realm: ${AUTH_SERVER_REALM}
      auth-server-url: "${EXTERNAL_ENDPOINT}"
      ssl-required: external
      resource: ${CLIENT_ID}
      public-client: false
      bearer-only: true
      confidential-port: 0
    session:
      secret: ${CLIENT_SECRET}
      resave: false
      saveUninitialized: true
