version: '3.3'
services:
  
  query-translator:
    image: docker-activage.satrd.es/querybuilder:1.1
    expose:
      - "4653"
    restart: unless-stopped
    environment:
      - "LOGIN_PATH=${BASE_URL_PROTOCOL}://${AIOTES_HOSTNAME}:${AIOTES_API_PORT}/services/fileserver/api/activage/login"
      - "ANALYTICS_URL=${BASE_URL_PROTOCOL}://${AIOTES_HOSTNAME}:${AIOTES_API_PORT}/analytics/"
      - "SEMANTIC_TRANSLATION=${BASE_URL_PROTOCOL}://${AIOTES_HOSTNAME}:${AIOTES_API_PORT}/services/jsontranslator/"
      - "DATA_LAKE=${BASE_URL_PROTOCOL}://${AIOTES_HOSTNAME}:${AIOTES_API_PORT}/datalake/dataIntegrationEngine"
      - "TRANFSER_FILES=${BASE_URL_PROTOCOL}://${AIOTES_HOSTNAME}:${AIOTES_API_PORT}/services/fileserver/api/activage"
      - "QUERY_TRANSLATION=${BASE_URL_PROTOCOL}://${AIOTES_HOSTNAME}:${AIOTES_API_PORT}/datalake/dataIntegrationEngine/querytranslation"
    command:
      - "/bin/bash"
      - "/usr/share/nginx/html/start.sh"

networks:
  default:
    external:
      name: aiotes

